<?php
/**
 * Created by PhpStorm.
 * User: si
 * Date: 2017/7/21
 * Time: 20:04
 */

namespace App\Api\Server;


use App\Ticket;
use app\Wechat\WxPayNotify;
use Illuminate\Support\Facades\Storage;

class WxServer extends WxPayNotify
{

    public function NotifyProcess($data, &$msg)
    {
     //   return parent::NotifyProcess($data, $msg); // TODO: Change the autogenerated stub

        if ($data['result_code'] == 'SUCCESS')
        {
            $tno = $data['out_trade_no'];
            $t = Ticket::where('tno',$tno)->first();

            $t->token = 'token';

            $t->update(['token'=>'token']);
            Storage::disk('local')->put('file.txt',$t);

        }
        else
        {
            return true;
        }


    }
}