<?php
/**
 * Created by PhpStorm.
 * User: si
 * Date: 2017/7/21
 * Time: 20:04
 */

namespace App\Api\Server;


use App\Ticket;
use app\Wechat\WxPayNotify;
use Illuminate\Support\Facades\Storage;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class WxServer extends WxPayNotify
{

    public function NotifyProcess($data, &$msg)
    {
     //   return parent::NotifyProcess($data, $msg); // TODO: Change the autogenerated stub

        if ($data['result_code'] == 'SUCCESS')
        {
            $tno = $data['out_trade_no'];
            $token = $this->getToken($tno);
            $t = Ticket::where(['tno'=>tno,'token'=>''])->first();
            Storage::disk('local')->put('file.txt',$t);

            if ($t) {
                $t->update(['token'=>$token]);
                $this->getQrCode($tno,$token);
            }

        }
        else
        {
            return true;
        }


    }

    public function getToken($tno){
        return bcrypt('NumberSi0102' . $tno);
    }

    public function getQrCode($tno,$token)
    {
        // $path = public_path('qrcodes/' . $filesName . '.png');
        $picturedata=  QrCode::format('png')->size(250)->generate($token);
        // $this->getImage($path);
        $disk = \Storage::disk('qiniu');
        $disk->put($tno.'.png',$picturedata);

    }

}